package com.babyduncan.dao;

import com.babyduncan.model.Student;
import com.babyduncan.model.StudentCriteria;
import com.babyduncan.model.StudentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    long countByExample(StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    int deleteByExample(StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    int insert(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    int insertSelective(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    List<StudentWithBLOBs> selectByExampleWithBLOBs(StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    List<Student> selectByExample(StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") StudentWithBLOBs record, @Param("example") StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") StudentWithBLOBs record, @Param("example") StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Nov 16 18:05:17 CST 2017
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentCriteria example);
}