package com.babyduncan.model;

import com.babyduncan.Gender;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class StudentWithBLOBs extends Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.avatar_bin
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private byte[] avatar_bin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.desc
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private byte[] desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public StudentWithBLOBs(Integer id, Gender gender, Byte grade, Short age, Long bookNum, Double score, BigDecimal total_score, String identify, String name, Date create_time, String status, byte[] avatar_bin, byte[] desc) {
        super(id, gender, grade, age, bookNum, score, total_score, identify, name, create_time, status);
        this.avatar_bin = avatar_bin;
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public StudentWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.avatar_bin
     *
     * @return the value of student.avatar_bin
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public byte[] getAvatar_bin() {
        return avatar_bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.avatar_bin
     *
     * @param avatar_bin the value for student.avatar_bin
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setAvatar_bin(byte[] avatar_bin) {
        this.avatar_bin = avatar_bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.desc
     *
     * @return the value of student.desc
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public byte[] getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.desc
     *
     * @param desc the value for student.desc
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setDesc(byte[] desc) {
        this.desc = desc;
    }
}