package com.babyduncan.model;

import com.babyduncan.Gender;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private Gender gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private Byte grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bookNum
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private Long bookNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.score
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.total_score
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private BigDecimal total_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.identify
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private String identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_time
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.status
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Student(Integer id, Gender gender, Byte grade, Short age, Long bookNum, Double score, BigDecimal total_score, String identify, String name, Date create_time, String status) {
        this.id = id;
        this.gender = gender;
        this.grade = grade;
        this.age = age;
        this.bookNum = bookNum;
        this.score = score;
        this.total_score = total_score;
        this.identify = identify;
        this.name = name;
        this.create_time = create_time;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Student() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setGender(Gender gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bookNum
     *
     * @return the value of student.bookNum
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Long getBookNum() {
        return bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bookNum
     *
     * @param bookNum the value for student.bookNum
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setBookNum(Long bookNum) {
        this.bookNum = bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.score
     *
     * @return the value of student.score
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.score
     *
     * @param score the value for student.score
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.total_score
     *
     * @return the value of student.total_score
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public BigDecimal getTotal_score() {
        return total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.total_score
     *
     * @param total_score the value for student.total_score
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setTotal_score(BigDecimal total_score) {
        this.total_score = total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.identify
     *
     * @return the value of student.identify
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.identify
     *
     * @param identify the value for student.identify
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setIdentify(String identify) {
        this.identify = identify == null ? null : identify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_time
     *
     * @return the value of student.create_time
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_time
     *
     * @param create_time the value for student.create_time
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.status
     *
     * @return the value of student.status
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.status
     *
     * @param status the value for student.status
     *
     * @mbg.generated Wed Dec 27 17:42:30 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}