package com.babyduncan.model;

import com.babyduncan.Gender;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private Gender gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bookNum
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private Long booknum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.score
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.total_score
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private BigDecimal totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.identify
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private String identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_time
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.status
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.avatar_bin
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private byte[] avatarBin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.desc
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private byte[] desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Student(Integer id, Gender gender, Integer grade, Short age, Long booknum, Double score, BigDecimal totalScore, String identify, String name, Date createTime, String status, byte[] avatarBin, byte[] desc) {
        this.id = id;
        this.gender = gender;
        this.grade = grade;
        this.age = age;
        this.booknum = booknum;
        this.score = score;
        this.totalScore = totalScore;
        this.identify = identify;
        this.name = name;
        this.createTime = createTime;
        this.status = status;
        this.avatarBin = avatarBin;
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Student() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setGender(Gender gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bookNum
     *
     * @return the value of student.bookNum
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Long getBooknum() {
        return booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bookNum
     *
     * @param booknum the value for student.bookNum
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setBooknum(Long booknum) {
        this.booknum = booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.score
     *
     * @return the value of student.score
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.score
     *
     * @param score the value for student.score
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.total_score
     *
     * @return the value of student.total_score
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public BigDecimal getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.total_score
     *
     * @param totalScore the value for student.total_score
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setTotalScore(BigDecimal totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.identify
     *
     * @return the value of student.identify
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.identify
     *
     * @param identify the value for student.identify
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setIdentify(String identify) {
        this.identify = identify == null ? null : identify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_time
     *
     * @return the value of student.create_time
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_time
     *
     * @param createTime the value for student.create_time
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.status
     *
     * @return the value of student.status
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.status
     *
     * @param status the value for student.status
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.avatar_bin
     *
     * @return the value of student.avatar_bin
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public byte[] getAvatarBin() {
        return avatarBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.avatar_bin
     *
     * @param avatarBin the value for student.avatar_bin
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setAvatarBin(byte[] avatarBin) {
        this.avatarBin = avatarBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.desc
     *
     * @return the value of student.desc
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public byte[] getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.desc
     *
     * @param desc the value for student.desc
     *
     * @mbg.generated Tue Jan 02 18:00:39 CST 2018
     */
    public void setDesc(byte[] desc) {
        this.desc = desc;
    }
}